/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gujvezbe;

import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author PreBoosted
 */
public class PostIt extends javax.swing.JFrame {

     private int xMousie;
     private int yMousie;
     private String userInput;
     private boolean small = true;
    public PostIt() {
        
        this.setUndecorated(true);
        this.setBackground(new Color(0, 255, 0, 0));
        
        
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        postItMainPanel = new javax.swing.JPanel();
        dragLabel = new javax.swing.JLabel();
        postItTextArea = new javax.swing.JTextArea();
        postItTextArea.setDocument(new Limtator(91));
        tglButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        postItMainPanel.setDoubleBuffered(false);
        postItMainPanel.setOpaque(false);
        postItMainPanel.setLayout(null);

        dragLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dragLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        dragLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        dragLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragLabelMouseDragged(evt);
            }
        });
        dragLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragLabelMousePressed(evt);
            }
        });
        postItMainPanel.add(dragLabel);
        dragLabel.setBounds(30, 0, 350, 30);

        postItTextArea.setBackground(new java.awt.Color(153, 255, 255));
        postItTextArea.setColumns(5);
        postItTextArea.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        postItTextArea.setForeground(new java.awt.Color(0, 0, 51));
        postItTextArea.setLineWrap(true);
        postItTextArea.setRows(4);
        postItTextArea.setAutoscrolls(false);
        postItTextArea.setBorder(null);
        postItTextArea.setCaretColor(new java.awt.Color(0, 0, 51));
        postItTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        postItTextArea.setOpaque(false);
        postItTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postItTextAreaMouseClicked(evt);
            }
        });
        postItTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                postItTextAreaKeyPressed(evt);
            }
        });
        postItMainPanel.add(postItTextArea);
        postItTextArea.setBounds(10, 40, 295, 140);

        tglButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/expandArrows.png"))); // NOI18N
        tglButton.setToolTipText("");
        tglButton.setAlignmentY(0.0F);
        tglButton.setBorder(null);
        tglButton.setBorderPainted(false);
        tglButton.setContentAreaFilled(false);
        tglButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tglButton.setDefaultCapable(false);
        tglButton.setFocusPainted(false);
        tglButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tglButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        tglButton.setIconTextGap(0);
        tglButton.setPreferredSize(new java.awt.Dimension(30, 25));
        tglButton.setRequestFocusEnabled(false);
        tglButton.setVerifyInputWhenFocusTarget(false);
        tglButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tglButton.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        tglButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tglButtonMouseReleased(evt);
            }
        });
        postItMainPanel.add(tglButton);
        tglButton.setBounds(0, 3, 30, 30);

        background.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/postitTest.png"))); // NOI18N
        background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        postItMainPanel.add(background);
        background.setBounds(0, 0, 400, 310);

        getContentPane().add(postItMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dragLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabelMousePressed
        xMousie = evt.getX();
        yMousie = evt.getY();
        
    }//GEN-LAST:event_dragLabelMousePressed

    private void dragLabelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragLabelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMousie -40, y - yMousie);
    }//GEN-LAST:event_dragLabelMouseDragged

    private void postItTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_postItTextAreaKeyPressed
       if(evt.getKeyCode() == 10 && evt.getModifiers() == 0){
           dragLabel.requestFocus();
          
       }
       if(evt.getKeyCode() == 10 && evt.getModifiers() == 1){
            postItTextArea.append(System.lineSeparator());
       }
    }//GEN-LAST:event_postItTextAreaKeyPressed

    private void postItTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postItTextAreaMouseClicked
   
    }//GEN-LAST:event_postItTextAreaMouseClicked

    private void tglButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tglButtonMouseReleased
        toggleSize();
    }//GEN-LAST:event_tglButtonMouseReleased
    private void toggleSize(){
        if(small){
            postItTextArea.setSize(370, 260);
            
            background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/postitTest 400 x300.png")));
          
            small = false;
        }else{
            
            
            postItTextArea.setSize(300, 140);
            background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/postitTest.png")));
           
            small = true;
        }
    }
  
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel dragLabel;
    private javax.swing.JPanel postItMainPanel;
    protected javax.swing.JTextArea postItTextArea;
    private javax.swing.JButton tglButton;
    // End of variables declaration//GEN-END:variables
}
